hints:
  - title_markdown: "How do I access the client's TCP connection?"
    body_markdown: |-
      Use the [`accept()`](https://man7.org/linux/man-pages/man2/accept.2.html) function to get the client connection:

      ```cpp
      int client_fd = accept(server_fd, (struct sockaddr*)&client_addr, (socklen_t*)&client_addr_len);
      ```

      The `accept()` function waits for an incoming connection, and then returns a new socket file descriptor for the client.
  - title_markdown: "How do I send a response to the client?"
    body_markdown: |-
      Use the [`send()`](https://man7.org/linux/man-pages/man2/send.2.html) function to send the response:

      ```cpp
      const char *response = "+PONG\r\n";
      send(client_fd, response, strlen(response), 0);
      ```

      `+PONG\r\n` is the string "PONG" encoded as a [RESP simple string](https://redis.io/docs/latest/develop/reference/protocol-spec/#simple-strings).
